<?php

/**
 * @file
 * Contains language_switcher_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function language_switcher_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the language_switcher_block module.
    case 'help.page.language_switcher_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Changes text of the language switcher block to a desired shortcode.') . '</p>';
      return $output;

    default:
  }
}
