minimum_single: 20
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 0
jquery_selector: 'select:visible'
search_contains: false
disable_search: true
allow_single_deselect: false
placeholder_text_multiple: 'Select multiple items'
placeholder_text_single: 'Select a single item'
no_results_text: 'No matching results'
disabled_themes:
  seven: '0'
  adminimal_theme: '0'
  tema: '0'
chosen_include: 2
_core:
  default_config_hash: JUHKHJeHl1bWXY41HMIcDR-VmAWvJ4OJycDubCkIeDU
